name: MeyPacks
version: '1.1.8'
main: com.github.meytiii.meypacks.MeyPacks
api-version: '1.21'
authors: [meytiii]
description: A Minecraft plugin for portal backpacks.
commands:
  meypack:
    description: Opens your portal backpack.
    usage: /<command>
    aliases: [mp]